### PR TITLE
Bug fix: Remove double parentheses from mask input names in documentation

### PR DESCRIPTION
**Pull request by mathieuboudreau**
Resolves issue #201 

(not 200, like the branch name was mistakenly was identified as).

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
@agahkarakuzu TRAVIS fails because no packages are installed. Is this a temporary TRAVIS issue, or something else?

```no packages installed.
????? lsqcurvefit does not exist in path
error: Lsqcurvefit could not be loaded properly
/home/travis/.travis/job_stages: line 169: 12905 Terminated              

travis_jigger $! $timeout $cmd
The command "travis_wait 30 octave --no-gui --eval "bootstrapTest;cd('/home/travis/build/neuropoly/qMRLab/Test/MoxUnitCompatible/quickMoxTests');res=moxunit_runtests('-recursive');exit(~res);"" exited with 1.
```

**Comment by agahkarakuzu** [comment]
@mathieuboudreau Apparently TRAVIS flushed our cache at some point. I will work on this today to fix it. I am planning to upload cache files (static ones) to the OSF so process won't be broken again.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau can you renew this pull request? Created cache cannot be used retrospectively I assume. I will find a proper solution to this.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu I don't think I have to re-create it, do I? I'll merge your other branch into master, then merge master into this one and restart the TRAVIS build – I think that should work?

**Comment by agahkarakuzu** [comment]
@mathieuboudreau thanks for the approval for PR, it is being merged. After `hotfix-travis` branch is merged, cache will be present in master. Then your solution should work.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau [this build](https://travis-ci.org/neuropoly/qMRLab/builds/370581956?utm_source=github_status&utm_medium=notification) will finish in approx 20 mins:

Till then, restarting build won't work.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu ok, I'll restart it after lunch then!

**Comment by agahkarakuzu** [comment]
@mathieuboudreau Push is passing, after that PR will just work fine.

**Pull request merged**
