### PR TITLE
IR params

### PR DESCRIPTION
**Pull request by ileppe**
- Explicit IR equations, based on sequence parameters.
Parameters (`M0`,`TR`,`FAinv`,`FAexcite`) can be entered in the `options` panel of each GUI (Sim_Single_Voxel_Curve_GUI, Sim_Multi_Voxel_Distribution_GUI, Sim_Sensitivity_Analysis_GUI) and the `fit` parameters will be automatically updated in the table on the right.
- Minor GUI element resizing
- Analytical equations (GRE-IR and SE-IR) public method for IR model 
- Bloch Simulator public method for IR model
- Changes ### and *** GUI element jokers to ## and **
- Increased version and patched IR & QSM models

### CODE REVIEW

**Comment by ileppe** [comment]
@mathieuboudreau I'm not sure what the travis error means, the log info is not very helpful?

**Comment by mathieuboudreau** [comment]
@ileppe hmm, I'm not sure. Our branch is out of date with the master branch, maybe something's wrong in master?

**Comment by mathieuboudreau** [comment]
We're facing a similar issue in the QSM pull request I think – I'll see if some of our debugging there helps out here.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau I restarted the failing job on QSM branch, I will see if issue persists.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu Next step could be to restart a Travis test on the last commit/PR pushed to master, if that one fails, then we've got other issues :/

**Comment by mathieuboudreau** [comment]
Testing a clean branch off of master passes the Travis tests (Noise_InversionTimes-2.html), so I guess the issue here is something else.

I'm going to update this branch with master, and then we can run the tests locally to see what MATLAB complains about.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau I've run the test that fails on Travis locally, it just worked, at least on Matlab. I did both:

`;res=moxunit_runtests('BatchExample_test.m','-with_coverage','-cover','/home/travis/build/neuropoly/qMRLab/src','-cover_exclude','*GUI*','-cover_json_file','coverage_BatchExample.json');`

and

`run BatchExample_test.m itself`

**Comment by mathieuboudreau** [comment]
On MATLAB 2018a and OSX, if I run

`res=moxunit_runtests('-recursive','/Users/mathieuboudreau/neuropoly/github/qMRLab/Test/MoxUnitCompatible/quickMoxTests')`

the test fails and I get the following output:

<details>

```

>> res=moxunit_runtests('-recursive','/Users/mathieuboudreau/neuropoly/github/qMRLab/Test/MoxUnitCompatible/quickMoxTests')
suite: 26 tests
.....................F.testing plotModel...
charmed...
dti...
noddi...
qmt_bssfp...
Warning: Ignoring extra legend entries. 
> In legend>set_children_and_strings (line 646)
  In legend>make_legend (line 316)
  In legend (line 259)
  In bSSFP_PlotSimCurve (line 42)
  In qmt_bssfp/plotModel (line 182)
  In plotmodel_test>test_plotmodel (line 18)
  In MOxUnitFunctionHandleTestCase/run (line 24)
  In MOxUnitTestSuite/run (line 53)
  In MOxUnitTestSuite/run (line 53)
  In moxunit_runtests>@()run(suite,test_report,params.partition_index,params.partition_count) (line 149)
  In moxunit_runtests>run_all_tests (line 207)
  In moxunit_runtests (line 102) 
qmt_sirfse...
Warning: Ignoring extra legend entries. 
> In legend>set_children_and_strings (line 646)
  In legend>make_legend (line 316)
  In legend (line 259)
  In SIRFSE_PlotSimCurve (line 14)
  In qmt_sirfse/plotModel (line 209)
  In plotmodel_test>test_plotmodel (line 18)
  In MOxUnitFunctionHandleTestCase/run (line 24)
  In MOxUnitTestSuite/run (line 53)
  In MOxUnitTestSuite/run (line 53)
  In moxunit_runtests>@()run(suite,test_report,params.partition_index,params.partition_count) (line 149)
  In moxunit_runtests>run_all_tests (line 207)
  In moxunit_runtests (line 102) 
qmt_spgr...
Warning: No MToff (i.e. no volumes acquired with Angles=0) --> Fitting assumes that MTData are already
normalized. 
> In qmt_spgr/plotModel (line 297)
  In plotmodel_test>test_plotmodel (line 18)
  In MOxUnitFunctionHandleTestCase/run (line 24)
  In MOxUnitTestSuite/run (line 53)
  In MOxUnitTestSuite/run (line 53)
  In moxunit_runtests>@()run(suite,test_report,params.partition_index,params.partition_count) (line 149)
  In moxunit_runtests>run_all_tests (line 207)
  In moxunit_runtests (line 102) 
inversion_recovery...
Warning: Ignoring extra legend entries. 
> In legend>set_children_and_strings (line 646)
  In legend>make_legend (line 316)
  In legend (line 259)
  In inversion_recovery/plotModel (line 196)
  In plotmodel_test>test_plotmodel (line 18)
  In MOxUnitFunctionHandleTestCase/run (line 24)
  In MOxUnitTestSuite/run (line 53)
  In MOxUnitTestSuite/run (line 53)
  In moxunit_runtests>@()run(suite,test_report,params.partition_index,params.partition_count) (line 149)
  In moxunit_runtests>run_all_tests (line 207)
  In moxunit_runtests (line 102) 
vfa_t1...
    M0: 2000
    T1: 0.7000

Warning: Ignoring extra legend entries. 
> In legend>set_children_and_strings (line 646)
  In legend>make_legend (line 316)
  In legend (line 259)
  In vfa_t1/plotModel (line 159)
  In plotmodel_test>test_plotmodel (line 18)
  In MOxUnitFunctionHandleTestCase/run (line 24)
  In MOxUnitTestSuite/run (line 53)
  In MOxUnitTestSuite/run (line 53)
  In moxunit_runtests>@()run(suite,test_report,params.partition_index,params.partition_count) (line 149)
  In moxunit_runtests>run_all_tests (line 207)
  In moxunit_runtests (line 102) 
mwf...
Warning: Ignoring extra legend entries. 
> In legend>set_children_and_strings (line 646)
  In legend>make_legend (line 316)
  In legend (line 259)
  In mwf/plotModel (line 211)
  In plotmodel_test>test_plotmodel (line 18)
  In MOxUnitFunctionHandleTestCase/run (line 24)
  In MOxUnitTestSuite/run (line 53)
  In MOxUnitTestSuite/run (line 53)
  In moxunit_runtests>@()run(suite,test_report,params.partition_index,params.partition_count) (line 149)
  In moxunit_runtests>run_all_tests (line 207)
  In moxunit_runtests (line 102) 
..TEST qMRusage...
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'DiffusionData', 'SigmaNoise', 'Mask'
   NOTE: data are 1D. For 4D datasets use FitData(data,Model)
   EXAMPLE:
         Model = charmed
         %% LOAD DATA
         data.DiffusionData = load_nii_data('DiffusionData.nii.gz');
         data.SigmaNoise = load_nii_data('SigmaNoise.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT A SINGLE VOXEL
         % Specific voxel:         datavox = extractvoxel(data,voxel);
         % Interactive selection:  datavox = extractvoxel(data);
         voxel       = round(size(data.DiffusionData(:,:,:,1))/2); % pick FOV center
         datavox     = extractvoxel(data,voxel);
         FitResults  = Model.fit(datavox);
         Model.plotModel(FitResults, datavox); % plot fit results
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'DiffusionData.nii.gz'); % use header from 'DiffusionData.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'DiffusionData', 'SigmaNoise', 'Mask'
   NOTE: data are 1D. For 4D datasets use FitData(data,Model)
   EXAMPLE:
         Model = dti
         %% LOAD DATA
         data.DiffusionData = load_nii_data('DiffusionData.nii.gz');
         data.SigmaNoise = load_nii_data('SigmaNoise.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT A SINGLE VOXEL
         % Specific voxel:         datavox = extractvoxel(data,voxel);
         % Interactive selection:  datavox = extractvoxel(data);
         voxel       = round(size(data.DiffusionData(:,:,:,1))/2); % pick FOV center
         datavox     = extractvoxel(data,voxel);
         FitResults  = Model.fit(datavox);
         Model.plotModel(FitResults, datavox); % plot fit results
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'DiffusionData.nii.gz'); % use header from 'DiffusionData.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'DiffusionData', 'Mask'
   NOTE: data are 1D. For 4D datasets use FitData(data,Model)
   EXAMPLE:
         Model = noddi
         %% LOAD DATA
         data.DiffusionData = load_nii_data('DiffusionData.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT A SINGLE VOXEL
         % Specific voxel:         datavox = extractvoxel(data,voxel);
         % Interactive selection:  datavox = extractvoxel(data);
         voxel       = round(size(data.DiffusionData(:,:,:,1))/2); % pick FOV center
         datavox     = extractvoxel(data,voxel);
         FitResults  = Model.fit(datavox);
         Model.plotModel(FitResults, datavox); % plot fit results
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'DiffusionData.nii.gz'); % use header from 'DiffusionData.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'Phase', 'Magn'
   EXAMPLE:
         Model = b0_dem
         %% LOAD DATA
         data.Phase = load_nii_data('Phase.nii.gz');
         data.Magn = load_nii_data('Magn.nii.gz');
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'Phase.nii.gz'); % use header from 'Phase.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'SF60', 'SF120'
   EXAMPLE:
         Model = b1_dam
         %% LOAD DATA
         data.SF60 = load_nii_data('SF60.nii.gz');
         data.SF120 = load_nii_data('SF120.nii.gz');
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'SF60.nii.gz'); % use header from 'SF60.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'MTon', 'MToff', 'Mask'
   EXAMPLE:
         Model = mt_ratio
         %% LOAD DATA
         data.MTon = load_nii_data('MTon.nii.gz');
         data.MToff = load_nii_data('MToff.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'MTon.nii.gz'); % use header from 'MTon.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'MTw', 'T1w', 'PDw', 'B1map', 'Mask'
   EXAMPLE:
         Model = mt_sat
         %% LOAD DATA
         data.MTw = load_nii_data('MTw.nii.gz');
         data.T1w = load_nii_data('T1w.nii.gz');
         data.PDw = load_nii_data('PDw.nii.gz');
         data.B1map = load_nii_data('B1map.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'MTw.nii.gz'); % use header from 'MTw.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'MTdata', 'R1map', 'Mask'
   NOTE: data are 1D. For 4D datasets use FitData(data,Model)
   EXAMPLE:
         Model = qmt_bssfp
         %% LOAD DATA
         data.MTdata = load_nii_data('MTdata.nii.gz');
         data.R1map = load_nii_data('R1map.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT A SINGLE VOXEL
         % Specific voxel:         datavox = extractvoxel(data,voxel);
         % Interactive selection:  datavox = extractvoxel(data);
         voxel       = round(size(data.MTdata(:,:,:,1))/2); % pick FOV center
         datavox     = extractvoxel(data,voxel);
         FitResults  = Model.fit(datavox);
         Model.plotModel(FitResults, datavox); % plot fit results
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'MTdata.nii.gz'); % use header from 'MTdata.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'MTdata', 'R1map', 'Mask'
   NOTE: data are 1D. For 4D datasets use FitData(data,Model)
   EXAMPLE:
         Model = qmt_sirfse
         %% LOAD DATA
         data.MTdata = load_nii_data('MTdata.nii.gz');
         data.R1map = load_nii_data('R1map.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT A SINGLE VOXEL
         % Specific voxel:         datavox = extractvoxel(data,voxel);
         % Interactive selection:  datavox = extractvoxel(data);
         voxel       = round(size(data.MTdata(:,:,:,1))/2); % pick FOV center
         datavox     = extractvoxel(data,voxel);
         FitResults  = Model.fit(datavox);
         Model.plotModel(FitResults, datavox); % plot fit results
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'MTdata.nii.gz'); % use header from 'MTdata.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'MTdata', 'R1map', 'B1map', 'B0map', 'Mask'
   NOTE: data are 1D. For 4D datasets use FitData(data,Model)
   EXAMPLE:
         Model = qmt_spgr
         %% LOAD DATA
         data.MTdata = load_nii_data('MTdata.nii.gz');
         data.R1map = load_nii_data('R1map.nii.gz');
         data.B1map = load_nii_data('B1map.nii.gz');
         data.B0map = load_nii_data('B0map.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT A SINGLE VOXEL
         % Specific voxel:         datavox = extractvoxel(data,voxel);
         % Interactive selection:  datavox = extractvoxel(data);
         voxel       = round(size(data.MTdata(:,:,:,1))/2); % pick FOV center
         datavox     = extractvoxel(data,voxel);
         FitResults  = Model.fit(datavox);
         Model.plotModel(FitResults, datavox); % plot fit results
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'MTdata.nii.gz'); % use header from 'MTdata.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'Data4D', 'Mask'
   EXAMPLE:
         Model = denoising_mppca
         %% LOAD DATA
         data.Data4D = load_nii_data('Data4D.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'Data4D.nii.gz'); % use header from 'Data4D.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'Data4D', 'NoiseMask'
   EXAMPLE:
         Model = noise_level
         %% LOAD DATA
         data.Data4D = load_nii_data('Data4D.nii.gz');
         data.NoiseMask = load_nii_data('NoiseMask.nii.gz');
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'Data4D.nii.gz'); % use header from 'Data4D.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'IRData', 'Mask'
   NOTE: data are 1D. For 4D datasets use FitData(data,Model)
   EXAMPLE:
         Model = inversion_recovery
         %% LOAD DATA
         data.IRData = load_nii_data('IRData.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT A SINGLE VOXEL
         % Specific voxel:         datavox = extractvoxel(data,voxel);
         % Interactive selection:  datavox = extractvoxel(data);
         voxel       = round(size(data.IRData(:,:,:,1))/2); % pick FOV center
         datavox     = extractvoxel(data,voxel);
         FitResults  = Model.fit(datavox);
         Model.plotModel(FitResults, datavox); % plot fit results
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'IRData.nii.gz'); % use header from 'IRData.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'VFAData', 'B1map', 'Mask'
   NOTE: data are 1D. For 4D datasets use FitData(data,Model)
   EXAMPLE:
         Model = vfa_t1
         %% LOAD DATA
         data.VFAData = load_nii_data('VFAData.nii.gz');
         data.B1map = load_nii_data('B1map.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT A SINGLE VOXEL
         % Specific voxel:         datavox = extractvoxel(data,voxel);
         % Interactive selection:  datavox = extractvoxel(data);
         voxel       = round(size(data.VFAData(:,:,:,1))/2); % pick FOV center
         datavox     = extractvoxel(data,voxel);
         FitResults  = Model.fit(datavox);
         Model.plotModel(FitResults, datavox); % plot fit results
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'VFAData.nii.gz'); % use header from 'VFAData.nii.gz'
 
fit
   Fit experimental data
   USAGE:
     FitResults = Model.fit(data)
   INPUT:
     data: [struct] containing: 'MET2data', 'Mask'
   NOTE: data are 1D. For 4D datasets use FitData(data,Model)
   EXAMPLE:
         Model = mwf
         %% LOAD DATA
         data.MET2data = load_nii_data('MET2data.nii.gz');
         data.Mask = load_nii_data('Mask.nii.gz');
         %% FIT A SINGLE VOXEL
         % Specific voxel:         datavox = extractvoxel(data,voxel);
         % Interactive selection:  datavox = extractvoxel(data);
         voxel       = round(size(data.MET2data(:,:,:,1))/2); % pick FOV center
         datavox     = extractvoxel(data,voxel);
         FitResults  = Model.fit(datavox);
         Model.plotModel(FitResults, datavox); % plot fit results
         %% FIT all voxels
         FitResults = FitData(data,Model);
         % SAVE results to NIFTI
         FitResultsSave_nii(FitResults,'MET2data.nii.gz'); % use header from 'MET2data.nii.gz'
 
.
--------------------------------------------------

failure: Error using loadModel_Test>load_test (line 37)
Missing field in inversion_recovery (version 2  0  6): savedProps(1).Sim_Single_Voxel_Curve_buttons is     'SNR'    [50]
, newProps(1).Sim_Single_Voxel_Curve_buttons is   Columns 1 through 11

    'SNR'    [50]    'T1'    [600]    'M0'    [1000]    'TR'    [3000]    'FAinv'    [180]    'FAexcite'

  Columns 12 through 14

    [90]    'Update input vari'    'pushbutton'


  load_test:37 (/Users/mathieuboudreau/neuropoly/github/qMRLab/Test/MoxUnitCompatible/quickMoxTests/loadModel_Test.m)

--------------------------------------------------

FAILED (passed=25, failure=1)

res =

  logical

   0


```

</details>

**Comment by mathieuboudreau** [comment]
Sounds like a patch is needed for retrocompatibility

**Comment by agahkarakuzu** [comment]
I've pushed new static model to see if it resolves the issue.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu thanks, but this goes against the design principles that we set. The solution to this issue is to write a patch and increase the qMRLab version, to ensure retrocompatibility.

**Comment by mathieuboudreau** [comment]
If this make the test pass and we push it, then other IR models that users have currently saved won't be loadable after this is merged to master.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau I know this violates our one and only principle regarding version increments :) I wanted to ensure that this is gonna solve it, then will revert the commit. if I am not mistaken, retrocompatibility only regards the consistency between obj fields. For example, would it still be complaining if I made a change in the methods where ir calculates `ra`?

**Comment by mathieuboudreau** [comment]
No, like you said, only fields I believe. This is so that saved models can be reloaded in future versions, not that it replicates the same results, so only things that are stored in the saved *.mat file matter.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau this one is still failing, any idea?

**Comment by mathieuboudreau** [comment]
From line 1579 of the Travis log, it appears that the last for tests are failing, do you know which ones these are in under the "quickMoxUnitTests" folder? 

`.................FFFFwarning: load: `

**Comment by agahkarakuzu** [comment]
There is one new test 'inversion_recovery_Test.m'. Test call is recursive on `travis.yml`, might there be something manual we need to do about it? On the other hand, it needs some refactoring.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu there's a conflict in this branch with master, regarding the file src/Common/tools/GenerateButtonsWithPanels.m . I think these are changes you've done in the QSM branch which you are more familiar with, could you take a look and resolve this conflict? I think we just want to keep the master changes, and discard the ones in this branch, but am not 100% sure as the one in this branch deals with a "##" joker whereas the one in master only deals with "###" and "***" jokers. Do we want to keep all three cases instead?

**Comment by ileppe** [comment]
@mathieuboudreau I had changed it to "##" because my option was only 2 characters to this was crashing. This checks if the 2 first characters are 'jokers', why do we need to also check "###"?

**Comment by mathieuboudreau** [comment]
@ileppe Ahh, I think because @agahkarakuzu was also developing new "jokers" for new features at the same time as you were, but in the QSM branch. @agahkarakuzu, do these two conflict? Technically, ## starts at every ###... Why don't we use unique "jokers" to avoid this?

**Comment by agahkarakuzu** [comment]
`###` was there for a quite while. At the beginning I tried to make it `####`, but then of course, any param name below 4 chars failed due to dimension mismatch. You can see my commit, where I reverted that change 8e59ca7dfe308d13ac279c540bca8a949e1559a7 and added `***` instead. We can reduce it down to two, but this will require further changes including `genvarname_v2.m` and manual entries in `UpdateFields` method of `qMT_SPGR.m` and some other models. 

Otherwise increasing/decreasing the number of # will cause problems.

**Comment by mathieuboudreau** [comment]
Maybe we could simply make the plot figure area smaller in height for the Sensivity Analysis GUI?

**Comment by ileppe** [comment]
@mathieuboudreau Do you want to just resize the box with the GUI editor?

**Comment by mathieuboudreau** [comment]
@ileppe I'm testing that now, it looks like it needs a bit of tweaking, but might work for me. I'll do it and then ask you to check on your screen to see if it looks OK for your resolution

**Comment by ileppe** [comment]
sure, I think I had already done that, but obviously not enough for a 13in screen! Sorry

**Comment by mathieuboudreau** [comment]
@ileppe Done. Pull and take a look to see if it looks decent on your resolution. Below is how it looks for me now.

sans titre

**Comment by ileppe** [comment]
@mathieuboudreau Sensitivity looks good but Multi Voxel Distribution looks like this:
qmrlab

**Comment by mathieuboudreau** [comment]
@ileppe hmm, I didnt touch that one - good catch!

**Comment by ileppe** [comment]
I must have done that, you fix or I fix?

**Comment by mathieuboudreau** [comment]
@ileppe I just made an attempt to fix that GUI area – pull and let me know if it looks good on your system!

**Comment by mathieuboudreau** [comment]
@agahkarakuzu the current test fails because the jokers saved in the model file are different in this version than in the old one, so I guess we need to write a patch for this?


```

failure: Missing field in qsm_sb (version 2   0  10): savedProps(1).buttons is 
{
  [1,1] = Derivative Direction
  [1,2] = 
  {
    [1,1] = forward
    [1,2] = backward
  }
  [1,3] = Sharp Filtering
  [1,4] = 1
  [1,5] = Sharp Mode
  [1,6] = 
  {
    [1,1] = once
    [1,2] = iterative
  }
  [1,7] = Padding Size
  [1,8] =

     9   9   9

  [1,9] = Magnitude Weighting
  [1,10] = 0
  [1,11] = PANEL
  [1,12] = Regularization Selection
  [1,13] =  4
  [1,14] = Split-Bregman
  [1,15] = 1
  [1,16] = ###L1 Regularized
  [1,17] = 0
  [1,18] = ###L2 Regularized
  [1,19] = 0
  [1,20] = ###No Regularization
  [1,21] = 0
  [1,22] = PANEL
  [1,23] = L1 Panel
  [1,24] =  3
  [1,25] = Lambda L1
  [1,26] =    9.2106e-04
  [1,27] = ReOptimize Lambda L1
  [1,28] = 0
  [1,29] = ***L1 Range
  [1,30] =

     -4.0000   -2.5000   15.0000

  [1,31] = PANEL
  [1,32] = L2 Panel
  [1,33] =  3
  [1,34] = Lambda L2
  [1,35] =  0.031623
  [1,36] = ReOptimize Lambda L2
  [1,37] = 0
  [1,38] = ***L2 Range
  [1,39] =

     -3    0   15

}
, newProps(1).buttons is 
{
  [1,1] = Derivative Direction
  [1,2] = 
  {
    [1,1] = forward
    [1,2] = backward
  }
  [1,3] = Sharp Filtering
  [1,4] = 1
  [1,5] = Sharp Mode
  [1,6] = 
  {
    [1,1] = once
    [1,2] = iterative
  }
  [1,7] = Padding Size
  [1,8] =

     9   9   9

  [1,9] = Magnitude Weighting
  [1,10] = 0
  [1,11] = PANEL
  [1,12] = Regularization Selection
  [1,13] =  4
  [1,14] = Split-Bregman
  [1,15] = 1
  [1,16] = ##L1 Regularized
  [1,17] = 0
  [1,18] = ##L2 Regularized
  [1,19] = 0
  [1,20] = ##No Regularization
  [1,21] = 0
  [1,22] = PANEL
  [1,23] = L1 Panel
  [1,24] =  3
  [1,25] = Lambda L1
  [1,26] =    9.2106e-04
  [1,27] = ReOptimize Lambda L1
  [1,28] = 0
  [1,29] = **L1 Range
  [1,30] =

     -4.0000   -2.5000   15.0000

  [1,31] = PANEL
  [1,32] = L2 Panel
  [1,33] =  3
  [1,34] = Lambda L2
  [1,35] =  0.031623
  [1,36] = ReOptimize Lambda L2
  [1,37] = 0
  [1,38] = **L2 Range
  [1,39] =

     -3    0   15

}
  loadModel_Test>load_test:37 (/home/jovyan/work/qMRLab/Test/MoxUnitCompatible/quickMoxTests/loadModel_Test.m)

--------------------------------------------------

```

**Comment by agahkarakuzu** [comment]
@mathieuboudreau omg! I was not expecting this! I think we should make save function get rid of them using `genvarname_v2`, what do you think?

**Comment by mathieuboudreau** [comment]
@agahkarakuzu hmm that sounds even messier, as then we'd have to somehow still track which options were hidden when the option is loaded. I think a patch is good enough, I don't even need to increment the patch version another time, since this PR already did that.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau At the beginning I thought that'd be awkward for users to see if they ever go and check a saved model. But, sure, we can keep it for another branch and patch for now.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu if anything, it has increased my understanding of what jokers do by like 20%.

**Comment by ileppe** [comment]
@mathieuboudreau Just pushed my fix for the GUI overlap. Please check whether it looks ok for you!

**Comment by mathieuboudreau** [comment]
@ileppe it looks ok on my end too!

**Comment by ileppe** [comment]
@mathieuboudreau @agahkarakuzu Thank YOUs TWOs!!! Fingers crossed, it'll pass...

**Comment by mathieuboudreau** [comment]
There's a minor issue – looks like the coverage isn't being uploaded to Coveralls.io. There might be an issue with our TRAVIS line where the coverage gets pulled, combined, then reuploaded, as I don't see the combined json file in the AWS folder for the latest job that passed.

**Comment by mathieuboudreau** [comment]
hmm, looks like Coveralls.io is having maintenance, must be due to that

**Pull request merged**
