### PR TITLE
fixed spelling

### PR DESCRIPTION
**Pull request by nnadeau**

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
For some unknown reason, TRAVIS isn't finding the AWS S3 credentials (used to upload coverage analysis reports for each test in stage 1) in the environment, even though they are set up and haven't been changed since I first created them:

travis

Initially I suspected that we hit the free tier usage limit for S3, but it appears we are well below thaqt:

s3

Let's wait a day, and if the Travis tests still fail tomorrow, @agahkarakuzu will create a new AWS account and setup his new keys and try with that. If that fails, we'll open an issue on the Travis Github page about it.

**Comment by spinicist** [comment]
I have heard via Twitter that the [travis.com / travis.org](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-app) changes are causing a lot of issues - would not be surprised if this is related given the timing

**Comment by mathieuboudreau** [comment]
Ahhh thanks for the heads up @spinicist ! I browsed their Issues page, but could not see anything recent that would relate to us. We'll wait to see if they sort this out soon.

**Comment by mathieuboudreau** [comment]
I think I've figured out the issue. All our other Travis test PRs and branches are passing – this is the first PR that's from an external fork. I'm wondering if Travis is looking for the AWS credentials on @nnadeau's account and isn't finding them there, so it's failing. Which is odd behaviour, because I'd expect Travis to use the environment variables of the project being merged into (since we're the ones requiring these tests).

One alternative would be to force merge this PR into a temporary branch (not master) on our repo (even though the Travis tests fails). Then, do another pull request from that branch into master, which would run the Travis tests with our credentials.

**Comment by mathieuboudreau** [comment]
So Travis-CI got back to me on twitter: https://twitter.com/travisci/status/1027285889263779840

It appears that the environment variables I set for the AWS S3 credentials are not included when running tests on external forks into this project on purpose.

As a short-term fix, I'll change the base branch of this PR to a new one (`pr254`), force merge into it (even though it fails – I can do that now that I have admin privileges), and then create a new PR from that branch to master so that the tests run.

In the longer term, we'll need to look into encrypting the S3 credentials and including them in the .travis.yml file (I tried to do that when I initially was setting up AWS S3 + Travis, but was unsuccessful then).

**Pull request merged**
