### PR TITLE
Add mt_ratio model

### PR DESCRIPTION
**Pull request by agahkarakuzu**
-- Add class definition under Magnetization_transfer 
-- Define class 
-- Link sample data

### CODE REVIEW

**Comment by agahkarakuzu** [comment]
@mathieuboudreau alright, I've already done that, but will do once again. Wishing your sister a lifetime happiness 🎆 Good luck!

**Comment by mathieuboudreau** [comment]
Thanks!

**Comment by agahkarakuzu** [comment]
- [ ] Have all tests passed on your local? 
- [ ] Are new features functional?
- [ ] Does the qMRLab GUI open?
- [ ] Can you change models?
- [ ] Can you load a data folder for a model?
- [ ] Can you view data?
- [ ] Can you zoom in the image?
- [ ] Can you pan out of the image?
- [ ] Can you view the histogram of the data?
- [ ] Can you change the color map?
- [ ] Can you fit dataset (Fit data)?
- [ ] Can you save/load the results?
- [ ] Can you open the options panel?
- [ ] Can you change option parameters?
- [ ] Can you save/load option paramters?
- [ ] Can you select a voxel?
- [ ] Can you fit the data of that voxel ("View data fit")?
- [ ] Can you simulate and fit a voxel ("Single Voxel Curve")?
- [ ] Can you run a Sensitivity Analysis?
- [ ] Can you simulate a Multi Voxel Distribution?

**Comment by mathieuboudreau** [comment]
@agahkarakuzu the first test is failing for some odd reason since I've updated your branch with master, but the log gets cutoff. Maybe run each test in the quickMOxTest folder on you local MATLAB installation to see where it's complaining?

**Comment by agahkarakuzu** [comment]
@mathieuboudreau I noticed that, I've found the reason why. I did not add object for the new model, doing it now.

**Pull request merged**
