### PR TITLE
New doc

### PR DESCRIPTION
**Pull request by tanguyduval**
Beautificalization + completion of the doc #120
Repair Travis

### CODE REVIEW

**Comment by tanguyduval** [comment]
#148 has some pending issues on vfa_t1 that need to be solved before merging this branch

**Comment by mathieuboudreau** [comment]
Thanks for working on all these fixes @tanguyduval ! I reversed the VFA protocol parameter name change that was causing the two Travis errors in 816ffd9.

A+

**Comment by mathieuboudreau** [comment]
@ileppe The tests now pass and you've been set as the reviewer for this pull request - feel free to do a pass over the recent changes and merge it at your convenience!

**Comment by ileppe** [comment]
All looks good on my end. The only thing that needs fixing is the 'auto_TOC.py' because I changed the layout of the .rst. I have already asked @gab-berest to take care of this and once that's done, we can merge! Thanks for all your work on this, guys @tanguyduval @mathieuboudreau !

**Comment by agahkarakuzu** [comment]
@tanguyduval @mathieuboudreau @ileppe Thank you all! Such a mint fresh look this merge menu has :) Hope to see the same for master. @ileppe batch example documentations are beautiful 👍 I will do minor modifications on the template to make them look better.

**Comment by ileppe** [comment]
Thanks @agahkarakuzu! Indeed, I think the layout needs a little work. e.g. the long lines like the references are illegible:
image

**Pull request merged**
