### PR TITLE
[NEW] Add ISO 8601 date/time format in FitResults output directory name

### PR DESCRIPTION
**Pull request by mathieuboudreau**
Resolves issue #228 

Output example: FitResults_2018-06-11T15-07-30

If a duplicate folder exists (which is unlikely, but could happen if someone changes timezones or when daylight savings time switches), then the it will add "_2" or whatever n'th folder it is to the end of the folder name.

I couldn't follow ISO 8601 exactly (2018-06-11T15:07:30) because MATLAB complained about the ":" symbol during startup (when adding folders to path). @ileppe do you have any other suggestions on formats of how the time could be displayed in the folder name? Or do you want to omit the time altogether and only save the date? I'm open to other formatting suggestions. Please test it out in the GUI to confirm that these changes work correctly for you.

### CODE REVIEW

**Comment by ileppe** [comment]
Sorry, I approved this too quickly, can you re-assign me pls @mathieuboudreau?
It seems to work well, but I think I would like something between the date and time, like `FitResults_2018-06-12_T12-57-56`, makes it a little easier to read. Or `FitResults_2018-06-12_T12.57.56`? What do you think? I made all the checks you mentioned in #213, and all works except the histogram (crashes). But I don't think this PR is the one that broke it. I will have to open another issue.

**Comment by mathieuboudreau** [comment]
@ileppe Thanks! I'd prefer `FitResults_2018-06-12_T12-57-56` over the other one, I'm not a fan of using periods in filenames (and particularly not in folder names). It is quite a pickle on how to make the time look nice, I wish the standard T12:57:65 would have worked for Matlab. Even the example above doesn't make it evident that it's time, but I'm not sure how 

Or how about even skipping the T and simply using an underscore? `FitResults_2018-06-12_12-57-56`

**Comment by mathieuboudreau** [comment]
@ileppe that's odd that the Histogram function crashes. I've just tested it using VFA data (B1 map) on another branch that's up to date with master (#218), and it worked. Could you give me more details on how/when it crashed for you?

**Comment by mathieuboudreau** [comment]
@ileppe I just checked, and the format `2018-06-12_12-57-56` is what's used in the AxonDeepSeg project – I think I'd like to stick with this format. If you're ok with this format, accept it so that I can merge it before the new release in a few hours. (It's fine otherwise, I can always add it to a rapid X.X.1 new minor release as soon as it get's approved, even while at the conference on my phone).

**Comment by mathieuboudreau** [comment]
Thanks for the quick response @ileppe ! See you in Paris!

**Pull request merged**
