### PR TITLE
VFA_T1 —> voxelwise = 1

### PR DESCRIPTION
**Pull request by tanguyduval**

### CODE REVIEW

**Comment by tanguyduval** [comment]
#105

**Comment by tanguyduval** [comment]
@ileppe please keep this branch separate (don't merge doc into this!) --> easier to merge
Please fix the Travis issues:
- add SimSingle Voxel Curve
- add plotModel
- plotModel should be runned without 
-  `st` or `lb` / `ub`  are required (used in Simulations or qMRusage)

**Comment by ileppe** [comment]
@tanguyduval, ok sorry, I wasn't aware it wasn't finished (I thought a pull request meant it was ready!). I already merged into doc and it was rather seamless. Would you like me to revert doc?
I'm thinking about working on these issues on a separate branch off doc.

**Comment by tanguyduval** [comment]
No, don't revert. Perfect. We just need to merge this branch before merging doc.
You can work on this branch (VFA_T1)

**Comment by ileppe** [comment]
@tanguyduval , what do you mean by
 * plotModel should be runned without inputs
?

**Comment by tanguyduval** [comment]
@ileppe the current Travis test for plotModel is: `Model.plotModel`
So you need to define default value if no inputs:
`if nargin<2, x.T1=1;`

**Comment by ileppe** [comment]
@tanguyduval ok thanks, got it.

**Comment by ileppe** [comment]
@tanguyduval : I did this on vfat1-irl. Pls check, thanks.

**Comment by tanguyduval** [comment]
moved to vfat1-irl

**Comment by tanguyduval** [comment]
@ileppe I just added Sim_Sensivity_Analysis and Multivoxel distrib in 7f0aacafdee0d257a75e0765c05e594fdd47335f

You automatically have them after adding Single Voxel Curve

**Pull request closed without merging**
