### PR TITLE
[TRAVIS] Fix Travis bug where travis passes even if MOx test returns a failure

### PR DESCRIPTION
**Pull request by mathieuboudreau**

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
@tanguyduval looks like this travis bug (that I inadvertently introduced) has been hiding a failing Travis test for a month, in the second test: https://travis-ci.org/neuropoly/qMRLab/jobs/416938201

Here is the most recent commit on master where the test passes: https://travis-ci.org/neuropoly/qMRLab/jobs/402244454

and here is the first appearance of the failure (which shows up as a green checkmark anyways): https://travis-ci.org/neuropoly/qMRLab/jobs/406391145

It appears this was introduced in the PR where you introduced the `range_outlier` function, and that it doesn't work well with empty matrices or something of the sort. Do you have any insight on how to fix this bug?

**Comment by tanguyduval** [comment]
@mathieuboudreau sovled
Hopefully I did not break everything 🤣

**Comment by mathieuboudreau** [comment]
@tanguyduval if the left side fails (e.g. sending the coverage report fails) , the or command (||) will execute the right side, which is a signal that tells travis to throw a failure for the test I believe. See: http://steven.casagrande.io/articles/travis-ci-and-if-statements/

**Comment by tanguyduval** [comment]
good! lets merge then 😄

**Comment by tanguyduval** [comment]
I let you delete the branch, ok?

**Pull request merged**
