### PR TITLE
Erika feedback

### PR DESCRIPTION
**Pull request by tanguyduval**
solves point 1/2/3 of issue #164

-  Add/Remove protocol lines:
image

- disable some options in qmt_spgr
image
For this, I added a feature. If you add "###" add the title of a button, this button is disabled. See `help GenerateButtonsWithPanels`.

- Change warning:
`Warning: No MToff (i.e. no volumes acquired with Angles=0) --> Fitting assumes that
MTData are already normalized. `

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
Does anyone have an idea as to why Travis is throwing this error?

`error: get_forge_pkg: could not read URL, please verify internet connection`

From a quick online search, it's related to installing certain Octave packages, I think.

**Comment by tanguyduval** [comment]
Oups, Travis cannot download the octave forge packages...
Trying to rebuild now, maybe it was a temporary server error

**Comment by mathieuboudreau** [comment]
Just FYI to all, in addition to the Travis error, Ilana and I are encountering several errors when trying to load images in the GUI. Ilana fixed one cell array index error, but there seems to be others that have propagated. 

Even if the TRAVIS test error is resolved, we should hold on merging this branch until the GUI-related errors are resolved, which are not caught by TRAVIS.

**Comment by tanguyduval** [comment]
@mathieuboudreau and @ileppe thank you for pointing this error! The behavior changed because NameID is now a string and this created lots of bug. 
I'm changing this variable back to a cell now (although that was a bit weird, but it was working), sorry...

Concerning the other Travis bugs, I solved them. I had to modify slightly the tests, such as 25bef2d107c44ab19c3d8428f04d64b6fd430f0f

I just added some corrections from feedbacks from Harris (e.g. could not plot the sequence diagram because the filename in the help changed (qMT_SPGR.png --> qmt_spgr.png))

Hopefully everything is working better now

**Comment by tanguyduval** [comment]
We have the `get_forge_pkg: could not read URL, please verify internet connection ` error again... Octave server has some issues. I'll retry in a tomorrow or later.

**Comment by mathieuboudreau** [comment]
Thanks @tanguyduval !! No worries!

**Comment by tanguyduval** [comment]
Concerning #170 
This is a very specific issue that I solved in d5e7075b9f781afc2347dbd08dc573d552fa369e directly in the CustomOption_GUI. The result is as follow:
image

If you agree I'll do the same trick for qmt_sirfse

**Comment by mathieuboudreau** [comment]
That looks good to me @tanguyduval ! Any way to align the text to the right for consistency? 

@ravenep what do you think?

**Comment by tanguyduval** [comment]
@mathieuboudreau I just restarted the build. This branch is ready for merging (if test pass)

**Pull request merged**
