### PR TITLE
Dti

### PR DESCRIPTION
**Pull request by tanguyduval**
- fill header
- correct bug
- FA is now 1rst output

todo:
- add option for non-linear (weighted) or linear fitting #176

### CODE REVIEW

**Comment by tanguyduval** [comment]
@ileppe I let you merge after review

**Comment by ileppe** [comment]
@agahkarakuzu there was a travis error related to libraries `error: __which__: /home/travis/octave/image-2.6.1/x86_64-pc-linux-gnu-api-v51/bwconncomp.oct: failed to load: liboctinterp.so.4: cannot open shared object file: No such file or directory` called from `SimTest_qmt_bssfp.m`. But went away when I re-launched it... Just putting it here in case it comes up again

**Comment by agahkarakuzu** [comment]
@ileppe It seems ok now, sometimes cache cannot be downloaded due to connection problems at server site. If cache is gonna cause too much trouble, I will keep those required files on OSF.

**Comment by ileppe** [comment]
@agahkarakuzu ok thanks!

**Pull request merged**
