### PR TITLE
Improve colorbar location & format

### PR DESCRIPTION
**Pull request by mathieuboudreau**
Resolves issue #153 

Changes:

- Move colorbar to the right of the MR images to avoid overlap
- Change colorbar text white -> black, size, and linewidth.
- Make the ROI tools use the same colorbar function (currently not in use, for future)

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
Note that the large quantity of commits listed are due to the recent squash & merge of doc, which this branch was branched off of. Master has since been merged into this branch; see file changes for detailed changes of this pull request.

**Comment by ileppe** [comment]
@mathieuboudreau Could you possibly shift the colorbar more to the right? It overlaps when the numbers are  >3 digits. Even with resizing, and especially on the black background, the values are not visible.
screen shot 2018-02-08 at 09 47 10

**Comment by mathieuboudreau** [comment]
@ileppe thanks for pointing that out! Is the bar that far left for any image that you produce? I ask because it technically *should* be anchored all the way to the right (that's how the `colorbar('Location', 'EastOutside',)` call works), so I'm a bit perplexed as to how it could be overlapping, since it's not happening to me. One thing that I could think of is that maybe that window was smaller than mine before the image was plotted, which would result in this, however the only fix for that I think would be either to 1) make the colorbar really really small for this case, but that would look badly on bigger screens, or 2) force a fixed window size so this never occurs.

Do you remember what are the approximate steps (data & whatever you were playing around with)  you took before this, so that I could try and reproduced it locally?

**Comment by mathieuboudreau** [comment]
@ileppe see issue #153 for screenshots of how it appears for me.

**Comment by ileppe** [comment]
You're right about the window re-sizing. If I open qMRLab and run the VFA_demo directly, I can't see  the numbers for M0 (4digits). If I re-size the main panel prior to running `Fit Data`, then I can. Maybe force the window to be bigger in the 1st place?

**Comment by mathieuboudreau** [comment]
This thread has a suggestion on how to force a minimum window size, this might be something we could play around with to solve this issue: https://www.mathworks.com/matlabcentral/answers/260761-how-to-limit-figure-size

**Comment by tanguyduval** [comment]
@mathieuboudreau you should merge asap to prevent future conflicts ;)
I just restarted the build that was crashing because of SourceForge server

**Pull request merged**
