### PR TITLE
Report bug

### PR DESCRIPTION
**Pull request by tanguyduval**
Add auto bug report for the GUI

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
@tanguyduval why do you propose to merge this branch into Toolbox_dependency instead of master?

**Comment by mathieuboudreau** [comment]
(That branch was merged on Friday): https://github.com/neuropoly/qMRLab/pull/240

**Comment by mathieuboudreau** [comment]
@tanguyduval You could just merge the minor changes from that into this one then, and then merge to master. Otherwise, if a reviewer didn't see this PR first, they could have merged the other branch (#248) before seeing that this one was intended for that one. Or, write a message in that PR saying to wait for this one to be merged.

Cheers,

Mathieu

**Comment by tanguyduval** [comment]
I close this PR and create a fresh new one then ;)

**Comment by mathieuboudreau** [comment]
@tanguyduval haha ok! Sorry for the hassle! I'm excited to try this branch out - thanks for this!

**Pull request closed without merging**
