### PR TITLE
Travis cache

### PR DESCRIPTION
**Pull request by agahkarakuzu**
Please see #185

### CODE REVIEW

**Comment by agahkarakuzu** [comment]
@mathieuboudreau Thank you for raising this point, you are right! I will make that startup test specific renaming it startup_test while we will still have a `startup.m ` for user end. I am still fighting caching strategies of Travis, but almost there.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau addressed `startup` issue, waiting for Travis completing its for boosted build for PR.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu Thanks! There still seems to be a block in startup.m that I'm curious about:

https://github.com/neuropoly/qMRLab/blob/6a192ce52cf3c5b3e6359141ecf9e20442a4160c/startup.m#L4-L26

If these Octave packages are already installed, will this block of code in startup.m reinstall them? Or will it skip the installation if the user already has these packages installed on their local computer? As I mentioned previously, startup.m is run everytime Octave/MATLAB is started.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau As you said, if those packages are pre-installed and octave knows where they are located, than `pkg load` will work (few seconds). If not, exception will be handled by installing packages via forge. Then, following runs on that computer should be able to use `pkg load`  each time qMRLab is started.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu Ahh I see I understand now - thanks!

**Comment by tanguyduval** [comment]
@agahkarakuzu in addition to my first comment on travis specific tempdir (see above), I see that the docs/source/_static/dti_batch_02.png has been changed to from FA to residue. FA is more interesting.
Best

**Comment by agahkarakuzu** [comment]
@tanguyduval I did not included any changes regarding what is displayed for dti. @ileppe is this something slipped past my attention for this merge or an intended change?

**Comment by ileppe** [comment]
@agahkarakuzu it looks like this merge will re-write the .png files, if you look at the history of 65638f4723a725a2ca7a7bdeb81dd7f2f5e85213
https://github.com/neuropoly/qMRLab/commits/65638f4723a725a2ca7a7bdeb81dd7f2f5e85213/docs/source/_static/dti_batch_02.png

**Comment by agahkarakuzu** [comment]
@tanguyduval It appears that when I pull from a branch using SourceTree, these png files are not updated. Although I was careful not to include them in my commits, I somehow ended up changing majority of those files (but not all of them, which is also interesting). 

Is there any preference on sourcetree to avoid this kind of complications?

**Comment by tanguyduval** [comment]
@agahkarakuzu When you merged with Ilana's branch, there were some conflicts on the .png files a6dd936a70006debf0424f515adde7612058b727
You did not commit Ilana's modifications at this step, but reset the files.
I know, Git is really complex and messy... Just regenerate the figs and we are fine.

Apart from that, it's the first time I see Travis crash after a merge. Sorry I cannot help you on the cache system, but feel free to correct comment and uncomment the lines directly on Master, so that Travis can generate the cache.

**Comment by agahkarakuzu** [comment]
@tanguyduval I've find out that there is this "use theirs" or "use mine" preference on SourceTree, which may prevent such problems. 

The reason master crashed after merge is that master cannot inherit cache from branches. Therefore, I made required changes on #187. This allowed master to store its cache. With Ilana's revert-png branch, master will be asked to use cache from now on. 

Hope that after this, new branches will inherit cache from master for push builds, and from other PRs for PR builds.

**Pull request merged**
