### PR TITLE
MT saturation - avoid division by 0, obtain percent unit

### PR DESCRIPTION
**Pull request by tanguyduval**

### CODE REVIEW

**Comment by tanguyduval** [comment]
looks good to me. @BeliveauP you can accept the review

**Comment by mathieuboudreau** [comment]
@tanguyduval @BeliveauP Instead of arbitrarily setting values of maps that are 0 to a small number, wouldn't it be better to use logical indexing when the MTSat is calculated to avoid fitting/calculating those voxels in the first place? That would speed up the overall calculations instead of needlessly calculating all the voxels that had 0 values. The only other step needed would be pre-allocating the MTsat variable so that the default values (uncalculated due to the logical indexing masking them out) are what you want them to be (likely NaN or 0).

**Comment by BeliveauP** [comment]
Yes that can be done, I'll make the changes,

Pascale Beliveau

**Comment by tanguyduval** [comment]
@BeliveauP two more features that would be great to add in this pull request:
1. Add the validation you did in a new test:
create a new test in folder test/moxunitcompatible that test the function "fit" for MTsat, and possibly all `voxelwise=false` Models (currently these models are not tested at all...). Use the datasets in folder Data.
2. Add R1 as a second output.

**Comment by tanguyduval** [comment]
@BeliveauP plz correct to use mask: issue #86

**Comment by tanguyduval** [comment]
@BeliveauP thanks for your modif.
if you are done, assign me as a reviewer

**Comment by tanguyduval** [comment]
ok @BeliveauP  I went over it and finished the correction. You can approve and merge! 
Would be great if @daryamor could test on the rat dataset with B1 correction :)

**Comment by tanguyduval** [comment]
@BeliveauP please use "Squash and Merge" in order to have only one commit message

**Comment by tanguyduval** [comment]
@daryamor tested and it worked, merging. Thanks @BeliveauP

**Pull request merged**
