### PR TITLE
Cosmetic

### PR DESCRIPTION
**Pull request by tanguyduval**
In this version I solved some DOC, GUI and installation issues (toolbox missing, fadeeva).
Notably: issues #222 #224 #124

### CODE REVIEW

**Comment by tanguyduval** [comment]
also all qMR* functions can now be run wo inputs

**Comment by mathieuboudreau** [comment]
Hi @tanguyduval,

Thanks for all these additions.

Unfortunately, I won't have time before ISMRM to review this pull request as I am flying out tomorrow, and have other PR's to review before making the new release tomorrow. These changes are too numerous and contain too many potential conflicting files (e.g. the qMRLab GUI changes here and in the ROI pull request can't be merged automatically) for me to review adequately, without letting bugs in accidentally right before ISMRM.

You didn't make us aware you were working on these features; in the future, it would be helpful if you opened issues before doing so, so that can be aware and don't accidentally double the work or work on conflicting files.

Lastly, please refrain from making jumbo pull requests containing commits full of unrelated features. Pull requests should resolve single issues/features at a time; that way, I might of had time to accept a few of them, or prioritise them.

I'll work on reviewing this ASAP when I get back the Monday after ISMRM.

**Comment by tanguyduval** [comment]
@mathieuboudreau I'll separate this PR in different PR (don't know how to do that properly yet, I'll take a look)

The story is that I tried to use qMRLab on my windows machine (no compiler, no toolbox) at the lab here... and I started to make some quick changes to make it work, and look nicer. Nothing big, but lots of small changes.

I'll follow this rule in the future: 1 issue/feature -> 1 pull request

best

**Comment by mathieuboudreau** [comment]
Ahh ok, no worries @tanguyduval . I can show you how to split up this PR and give you a hand witht it when I get back.

See you at ISMRM!

**Comment by tanguyduval** [comment]
ok merge splited

**Comment by mathieuboudreau** [comment]
Thanks @tanguyduval ! I'll start reviewing them once they pass the Travis tests!

**Pull request closed without merging**
